services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    restart: unless-stopped
    ports:
      - "11090:9090"
    volumes:
      - /data/prometheus/config:/etc/prometheus
      - /data/prometheus/data:/prometheus
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512M
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    restart: unless-stopped
    ports:
      - "11091:9100"
    command:
      - --path.rootfs=/host
    volumes:
      - /:/host:ro,rslave
    deploy:
      resources:
        limits:
          memory: 512M
        reservations:
          memory: 128M
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
