services:
  elasticsearch:
    container_name: elasticsearch
    # image: elasticsearch:8.12.2
    image: docker.cnb.cool/jinriyaojia_huigu/yaocai/devops/elasticsearch:8.12.2
    restart: unless-stopped
    user: 1000:1000
    environment:
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g -XX:+UseG1GC"
      # 禁用 HTTPS，启用 HTTP
      - "xpack.security.http.ssl.enabled=false"
      - "xpack.security.enabled=true"  # 保持安全启用，但使用 HTTP
      - "discovery.type=single-node"
      - "ingest.geoip.downloader.enabled=false"
      - "ELASTIC_PASSWORD=${ELASTIC_PASSWORD}"
    ports:
      - "19200:9200"  # Elasticsearch 默认的 HTTP 端口，用于接收 REST API 请求，比如搜索、索引文档等操作
      # - "19300:9300"  # Elasticsearch 默认的 Transport 端口，用于节点间通信和 Java 客户端的传输层连接
    volumes:
      - ./runtime/es/config:/usr/share/elasticsearch/config
      - ./runtime/es/data:/usr/share/elasticsearch/data
      - ./runtime/es/plugins:/usr/share/elasticsearch/plugins
      - ./runtime/es/logs:/usr/share/elasticsearch/logs  # 挂载日志目录
    networks:
      - elastic_net
    ulimits:
      nofile:
        soft: 65535
        hard: 65535
      nproc:
        soft: 4096
        hard: 4096
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits:
          memory: 2G
          cpus: '2.0'
        reservations:
          memory: 1G
          cpus: '1'
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
  kibana:
    container_name: kibana
    # image: kibana:8.12.2
    image: docker.cnb.cool/jinriyaojia_huigu/yaocai/devops/kibana:8.12.2
    restart: unless-stopped
    environment:
      - "TZ=Asia/Shanghai"
      - "I18N_LOCALE=zh-CN"
      - "ELASTICSEARCH_SSL_VERIFICATIONMODE=none"  # 开发环境禁用证书验证
      # 禁用不需要的功能
      - "XPACK_SECURITY_LOGIN_HELP_ENABLED=false"
      - "XPACK_SECURITY_PASSWORD_RESET_ENABLED=false"
      - "XPACK_SECURITY_SESSION_IDLE_TIMEOUT=1h"
      - "SERVER_HOST=0.0.0.0"
      - "SERVER_NAME=kibana"
      - "NODE_OPTIONS=--max-old-space-size=800"  # 设置 Node.js 最大堆内存为 800MB
      - "ELASTICSEARCH_HOSTS=http://elasticsearch:9200"
      # 1.1账号验证
      - "ELASTICSEARCH_USERNAME=kibana_system"
      - "ELASTICSEARCH_PASSWORD=${KIBANA_PASSWORD}"
      # 1.2服务账户令牌
      # - "ELASTICSEARCH_SERVICEACCOUNTTOKEN=AAEAAWVsYXN0aWMva2liYW5hL2tpYmFuYS10b2tlbjpWckFhYWl4U1EyNmNRMGR4OGtXYmVR"
    ports:
      - "5601:5601"
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
    networks:
      - elastic_net
    depends_on:
      - elasticsearch

# 网络配置
networks:
  elastic_net:
    driver: bridge
