"""init

Revision ID: 029af03489de
Revises: 
Create Date: 2025-07-15 17:24:53.890642

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '029af03489de'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='公司ID'),
    sa.Column('company_name', sa.String(length=100), nullable=True, comment='公司名称'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('events', mysql.JSON(), nullable=False, comment='事件内容'),
    sa.Column('payload', mysql.JSON(), nullable=True, comment='附加数据'),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='请求ID，前端生成并保存至localstorage'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('events')
    # ### end Alembic commands ###
