"""feat event detail seq

Revision ID: 2d9880317681
Revises: eba652be0833
Create Date: 2026-09-05 11:23:31.442294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d9880317681'
down_revision: Union[str, None] = 'eba652be0833'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrweb_event_details', sa.Column('seq', sa.Integer(), nullable=True, comment='同一会话内分片序号（前端单调递增；空则回放按 id）'))
    op.create_unique_constraint('uq_rrweb_event_details_session_seq', 'rrweb_event_details', ['session_id', 'seq'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_rrweb_event_details_session_seq', 'rrweb_event_details', type_='unique')
    op.drop_column('rrweb_event_details', 'seq')
    # ### end Alembic commands ###
