"""feat: session is_locked

Revision ID: c01b2fb0e20f
Revises: 2d9880317681
Create Date: 2026-09-10 16:38:17.145213

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c01b2fb0e20f'
down_revision: Union[str, None] = '2d9880317681'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rrweb_sessions', sa.Column('is_locked', sa.SmallInteger(), server_default='0', nullable=False, comment='是否锁定：1=锁定，禁止删除与清理'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rrweb_sessions', 'is_locked')
    # ### end Alembic commands ###
