"""feat: 请求时间字段

Revision ID: dfe6226ef844
Revises: 029af03489de
Create Date: 2025-07-22 15:56:42.666067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dfe6226ef844'
down_revision: Union[str, None] = '029af03489de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('events', sa.Column('request_at', sa.DateTime(), nullable=True, comment='请求时间'))
    op.create_index(op.f('ix_events_id'), 'events', ['id'], unique=False)
    op.create_index(op.f('ix_events_request_at'), 'events', ['request_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_events_request_at'), table_name='events')
    op.drop_index(op.f('ix_events_id'), table_name='events')
    op.drop_column('events', 'request_at')
    # ### end Alembic commands ###
