"""feat: 录屏双表拆分

Revision ID: eba652be0833
Revises: dfe6226ef844
Create Date: 2026-08-25 16:01:33.631946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'eba652be0833'
down_revision: Union[str, None] = 'dfe6226ef844'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rrweb_event_details',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('session_id', sa.Integer(), nullable=False, comment='所属会话ID'),
    sa.Column('events', mysql.JSON(), nullable=False, comment='事件内容'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rrweb_event_details_id'), 'rrweb_event_details', ['id'], unique=False)
    op.create_index(op.f('ix_rrweb_event_details_session_id'), 'rrweb_event_details', ['session_id'], unique=False)
    op.create_table('rrweb_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', sa.DateTime(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', sa.DateTime(), nullable=True, comment='更新时间'),
    sa.Column('request_id', sa.String(length=50), nullable=False, comment='请求ID，前端生成并保存至 sessionStorage'),
    sa.Column('company_id', sa.Integer(), nullable=True, comment='公司ID'),
    sa.Column('company_name', sa.String(length=100), nullable=True, comment='公司名称'),
    sa.Column('user_id', sa.Integer(), nullable=True, comment='用户ID'),
    sa.Column('user_name', sa.String(length=100), nullable=True, comment='用户名'),
    sa.Column('record_type', sa.SmallInteger(), server_default='1', nullable=False, comment='录屏类型：1=采购订单录屏'),
    sa.Column('payload', mysql.JSON(), nullable=True, comment='附加数据（含 order_plan_id 等）'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id', 'company_id', 'user_id', name='uq_rrweb_sessions_request_company_user')
    )
    op.create_index(op.f('ix_rrweb_sessions_id'), 'rrweb_sessions', ['id'], unique=False)
    op.drop_index('ix_events_id', table_name='events')
    op.drop_index('ix_events_request_at', table_name='events')
    op.drop_table('events')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('events',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False, comment='主键ID'),
    sa.Column('created_at', mysql.DATETIME(), nullable=True, comment='创建时间'),
    sa.Column('updated_at', mysql.DATETIME(), nullable=True, comment='更新时间'),
    sa.Column('company_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='公司ID'),
    sa.Column('company_name', mysql.VARCHAR(length=100), nullable=True, comment='公司名称'),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True, comment='用户ID'),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True, comment='用户名'),
    sa.Column('events', mysql.JSON(), nullable=False, comment='事件内容'),
    sa.Column('payload', mysql.JSON(), nullable=True, comment='附加数据'),
    sa.Column('request_id', mysql.VARCHAR(length=50), nullable=False, comment='请求ID，前端生成并保存至localstorage'),
    sa.Column('request_at', mysql.DATETIME(), nullable=True, comment='请求时间'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_index('ix_events_request_at', 'events', ['request_at'], unique=False)
    op.create_index('ix_events_id', 'events', ['id'], unique=False)
    op.drop_index(op.f('ix_rrweb_sessions_id'), table_name='rrweb_sessions')
    op.drop_table('rrweb_sessions')
    op.drop_index(op.f('ix_rrweb_event_details_session_id'), table_name='rrweb_event_details')
    op.drop_index(op.f('ix_rrweb_event_details_id'), table_name='rrweb_event_details')
    op.drop_table('rrweb_event_details')
    # ### end Alembic commands ###
