services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "11080:8080"
      - "11081:50000"
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      # - /root/.ssh:/root/.ssh
      - /www/wwwroot:/dist
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Xmx4g -Xms1g
    privileged: true
    user: root
    deploy:
      resources:
        limits:
          memory: 4G
        reservations:
          memory: 1G
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
