services:
  jenkins:
    image: jenkins/jenkins:2.426.2-lts
    container_name: jenkins
    restart: unless-stopped
    ports:
      - "11080:8080"
      - "11081:50000"
    volumes:
      - /data/jenkins/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - JAVA_OPTS=-Djava.awt.headless=true -Xmx2g -Xms512m
    privileged: true
    user: root
    deploy:
      resources:
        limits:
          memory: 2G
        reservations:
          memory: 512m
    logging:
      driver: json-file
      options:
        max-size: "30m"
        max-file: "10"
